version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: uniqly
    restart: always
  web:
    build: .
    environment:
      PGHOST: db
      PGPORT: 5432
      DBNAME: uniqly
      HOSTNAME: 172.17.0.1
    depends_on:
      - db
    ports:
      - "3001:3001"
    restart: always
